# Composite Action; Locally so only can be used here
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  caching:
    description: 'whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install.outputs.cache }}

runs:
  # custom composite action
  using: 'composite'
  steps:
     - name: Cache dependencies
       if: inputs.caching == 'true'
       id: cache
       uses: actions/cache@v3
       with:
         path: node_modules
         key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
     - name: Install dependencies
       id: install
       if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
       run: |
         npm ci
         echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
       # which shell to execute the run
       # only for custom actions
       shell: bash

